name: Test Python Package from Nexus

on:
  push:
    branches:
      - implements

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3
      
      - name: Set up Python
        uses: actions/setup-python@4
        with:
          python-version: '3.10'

      - name: Install dependency from Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWD }}
        run: |
          pip install milib-ejemplo \
            --index-url http://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@